# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-27 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagegroup',
            old_name='advisor',
            new_name='user_to',
        ),
    ]
